### ISSUE TITLE
README format

### ISSUE THREAD

**Issue by Sazaju** [MGQ-EX/Paradox#1]
You should replace "README.md" by "README.txt", bcause you are not at all using Markdown conventions, so the display is completely ruined. Use the txt extension so it take it as a simple, unformatted text file, which should render better. Otherwise you should think to revise deeply the content to properly format it as a Markdown file.

**Comment by MGQ-EX** [comment]
Sazaju,

Thank you for pointing that out.  Later I'm gonna give the whole thing a
more thorough review.

Regards,
MGQ EX

**Comment by Sazaju** [comment]
Better that way. {^_^}b

2015-08-01 3:49 GMT+02:00 MGQ EX notifications@github.com:
