### ISSUE TITLE
Bloody Lightning Thrust missing "(Att)" on the description

### ISSUE THREAD

**Issue by LostDGod** [MGQ-EX/Paradox#2]
Line 14829
ORIGINAL:
Power:C *\ie[5]+ Target:Foe Effect: Swift Strike,+

FIXED:
Power:C (Att)*\ie[5]+ Target:Foe Effect: Swift Strike,+

Sorry this is not really a bug I'm not sure if I should post these errors here so redirect me if I'm not supposed to.

**Comment by MGQ-EX** [comment]
It's a bug LostDGod, thank you for finding it.  If you say its for the Database effects skills/938/description instead of Line X though it makes it faster to find in the file.  Changes should now be on the developers build and will be incorporated in the next release
