### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LostDGod** [MGQ-EX/Paradox#4]
Found a crash error that happens when you try to leave the config menu during a fight. It might be related to the HP bars.
- Tested with all the main options from game.ini On and Off and crashed every time. 
- It works fine outside the fights.
- Tested with an earlier EX version (not sure but probably 0.5h) and there is no crash there.
- Added the native HP Bars script to the script file of the earlier EX version I have and there is no crash there either.

Screenshot link: http://imgur.com/XS9yySG

**Comment by MGQ-EX** [comment]
Seems to be a problem with the HP bars and Config, Config on closing removes all windows and HP bars doesn't recreate them right after and is looking to see if one is active;  Will be patched in 0.5l, Thanks for bringing it up
