### ISSUE TITLE
Small Typo Bug

### ISSUE THREAD

**Issue by LostDGod** [MGQ-EX/Paradox#5]
On DatabaseTextEnglish:

skills/2493/description
Power300%*\ie[2](Dex) Target:Foe Effect: HP Drain 50%

Displays percentage instead of rank and there's also no " : " after " Power".

**Comment by LostDGod** [comment]
Tried to find similar typos through notepad++ found one:
skills/2654/description
Power:700%(Current HP) Target:All Foes

Scratch that, it doesn't make much sense to rank this one if it uses Current HP as a multiplier for the dmg... or does it? Skills 1666 and 2988 are similar and follow the rank system. You might want to change those or fix the one I first mentioned above.

**Comment by MGQ-EX** [comment]
Typo In skills/2493/description changed to "Power: E"
skills 1666, 2988, and 2654 roughtly translates To "Power: Variable" Dargoth's version pulls that info from the backend but for that its more then 'Variable'';  Tried to convert Dargoth's Percentage Charts to Ranks but there was inaccuracy so the Japanese version was used to compare most but anything generic like Variable I left it as it offers some information.  Thanks for finding the typo
